#!/bin/bash

mkdir -p /etc/gammabyte/lsapi

dnf -y install libvirt libvirt-devel mariadb-server virt-install go gcc
systemctl enable mariadb --now
systemctl enable libvirtd --now

read -p "MySQL User (cannot be 'root'): " mySqlUser
read -r -s -p "MySQL Password: " mySqlPass
read -p "VM Volume Location (trailing slash needed): " volumeLocation
read -p "API Listen Port: " listenPort
read -p "API Listen Address: " listenAddress
read -p "Default Domain Bandwidt (megabits): " domainBandwidth
read -p "VM Manufacturer (ex. yourdomain.com): " domainManufacturer

cat <<EOT > /etc/gammabyte/lsapi/config.yml
volume_path: "$volumeLocation"
# This is where your VM volumes will be stored (required)
listen_port: "$listenPort"
# This is the port the API will listen on (required)
listen_address: "$listenAddress"
# This is the address it will listen on (required)
sql_password: "$mySqlPass"
# This is the password for MariaDB (required)
vm_manufacturer: "$domainManufacturer"
# This will be the sysinfo manufacturer entry (below 16 characters!!) (required)
sql_user: "$mySqlUser"
# This is the user to access MariaDB with (needs full privileges) (required)
domain_bandwidth: $domainBandwidth
# This is the network bandwidth, in Mbps, that the VMs being provisioned will be allowed to communicate over the network with (required)
virtual_network_subnet: "10.1.1"
# The first three values for the subnet to provision VMs on. This may change to be inside any local address space. The subnet mask is 24. (Ex. 10.1.1, 10.1.2, 192.168.0, 172.16.0) (required)
EOT

echo "Creating database 'lsapi'"
mysql -e "CREATE DATABASE lsapi /*\!40100 DEFAULT CHARACTER SET utf8 */;"
echo "Creating user $mySqlUser"
mysql -e "CREATE USER ${mySqlUser}@localhost IDENTIFIED BY '${mySqlPass}';"
echo "Granting all privileges to $mySqlUser on DB 'lsapi'"
mysql -e "GRANT ALL PRIVILEGES ON lsapi.* TO ${mySqlUser}@localhost IDENTIFIED BY '${mySqlPass}';"
echo "Flushing privileges..."
mysql -e "FLUSH PRIVILEGES;"
echo "Creating tables & columns..."
mysql -e "CONNECT lsapi; CREATE TABLE IF NOT EXISTS domaininfo(domain_name text, network text, mac_address text, ip_address text, disk_path text, time_created text, user_email text, user_full_name text, username text)"
echo "Done creating MySQL DB!"

go mod download
go mod verify
go build main.go
